// flow-typed signature: c213ad7223f1c5c4faed47834fbf2329
// flow-typed version: <<STUB>>/@glennsl/bs-revamp_v^0.1.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@glennsl/bs-revamp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@glennsl/bs-revamp' {
  declare module.exports: any;
}
