// flow-typed signature: 3be549996e42551ccb20b2e12b22c2d6
// flow-typed version: <<STUB>>/bs-webapi_v^0.11.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-webapi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-webapi' {
  declare module.exports: any;
}
