// flow-typed signature: e378cbfcaf4c131a1468835f8b9475ad
// flow-typed version: <<STUB>>/stack-styled_v^0.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stack-styled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stack-styled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stack-styled/esm/Stack' {
  declare module.exports: any;
}

declare module 'stack-styled/lib/Stack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stack-styled/esm/Stack.js' {
  declare module.exports: $Exports<'stack-styled/esm/Stack'>;
}
declare module 'stack-styled/lib/Stack.js' {
  declare module.exports: $Exports<'stack-styled/lib/Stack'>;
}
