// flow-typed signature: 45cba7ab473957468c8e096edbe9cb6b
// flow-typed version: <<STUB>>/storybook-chromatic_vlatest/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-chromatic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-chromatic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-chromatic/dist/assets/environment' {
  declare module.exports: any;
}

declare module 'storybook-chromatic/dist/assets/null-server' {
  declare module.exports: any;
}

declare module 'storybook-chromatic/dist/assets/storybook-addon' {
  declare module.exports: any;
}

declare module 'storybook-chromatic/dist/bin/chromatic-test' {
  declare module.exports: any;
}

declare module 'storybook-chromatic/dist/bin/chromatic' {
  declare module.exports: any;
}

declare module 'storybook-chromatic/dist/client' {
  declare module.exports: any;
}

declare module 'storybook-chromatic/dist/tester' {
  declare module.exports: any;
}

declare module 'storybook-chromatic/storybook-addon' {
  declare module.exports: any;
}

declare module 'storybook-chromatic/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-chromatic/dist/assets/environment.js' {
  declare module.exports: $Exports<'storybook-chromatic/dist/assets/environment'>;
}
declare module 'storybook-chromatic/dist/assets/null-server.js' {
  declare module.exports: $Exports<'storybook-chromatic/dist/assets/null-server'>;
}
declare module 'storybook-chromatic/dist/assets/storybook-addon.js' {
  declare module.exports: $Exports<'storybook-chromatic/dist/assets/storybook-addon'>;
}
declare module 'storybook-chromatic/dist/bin/chromatic-test.js' {
  declare module.exports: $Exports<'storybook-chromatic/dist/bin/chromatic-test'>;
}
declare module 'storybook-chromatic/dist/bin/chromatic.js' {
  declare module.exports: $Exports<'storybook-chromatic/dist/bin/chromatic'>;
}
declare module 'storybook-chromatic/dist/client.js' {
  declare module.exports: $Exports<'storybook-chromatic/dist/client'>;
}
declare module 'storybook-chromatic/dist/tester.js' {
  declare module.exports: $Exports<'storybook-chromatic/dist/tester'>;
}
declare module 'storybook-chromatic/storybook-addon.js' {
  declare module.exports: $Exports<'storybook-chromatic/storybook-addon'>;
}
declare module 'storybook-chromatic/webpack.config.babel.js' {
  declare module.exports: $Exports<'storybook-chromatic/webpack.config.babel'>;
}
