// flow-typed signature: 88ed022284576d0305a1e83326c9a7fd
// flow-typed version: <<STUB>>/dependency-env_v^0.1.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dependency-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dependency-env' {
  declare module.exports: any;
}
