// flow-typed signature: 884a06fe2be9a3d8e26da0cb05b7a848
// flow-typed version: <<STUB>>/draftjs-utils_v^0.9.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draftjs-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draftjs-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draftjs-utils/lib/draftjs-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draftjs-utils/lib/draftjs-utils.js' {
  declare module.exports: $Exports<'draftjs-utils/lib/draftjs-utils'>;
}
