// flow-typed signature: 271b1c6a7a5f6875e61110b9b32d1f9d
// flow-typed version: <<STUB>>/draftjs-md-converter_v^1.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draftjs-md-converter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draftjs-md-converter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draftjs-md-converter/dist/index' {
  declare module.exports: any;
}

declare module 'draftjs-md-converter/src/draftjsToMd' {
  declare module.exports: any;
}

declare module 'draftjs-md-converter/src/mdToDraftjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draftjs-md-converter/dist/index.js' {
  declare module.exports: $Exports<'draftjs-md-converter/dist/index'>;
}
declare module 'draftjs-md-converter/src/draftjsToMd.js' {
  declare module.exports: $Exports<'draftjs-md-converter/src/draftjsToMd'>;
}
declare module 'draftjs-md-converter/src/mdToDraftjs.js' {
  declare module.exports: $Exports<'draftjs-md-converter/src/mdToDraftjs'>;
}
