// flow-typed signature: 2c1b028b4acebd0513c59db3512e456d
// flow-typed version: <<STUB>>/highlightjs-solidity_v^1.0.5/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highlightjs-solidity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'highlightjs-solidity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highlightjs-solidity/solidity' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highlightjs-solidity/solidity.js' {
  declare module.exports: $Exports<'highlightjs-solidity/solidity'>;
}
