// flow-typed signature: 85d8046909926ede66af51dde7c39fdc
// flow-typed version: <<STUB>>/next-plugin-transpile-modules_v^0.1.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-plugin-transpile-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-plugin-transpile-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-plugin-transpile-modules/index' {
  declare module.exports: $Exports<'next-plugin-transpile-modules'>;
}
declare module 'next-plugin-transpile-modules/index.js' {
  declare module.exports: $Exports<'next-plugin-transpile-modules'>;
}
