// flow-typed signature: 3bb1456c673f4ccbd0e20a5be3655de2
// flow-typed version: <<STUB>>/@storybook/core_v4.0.0-alpha.16/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/core/client' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/index' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/manager/index' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/manager/preview' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/manager/provider' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/client_api' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/config_api' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/reducer' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/start' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/story_store' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/subscriptions_store' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/syncUrlWithStore' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/build-dev' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/build-static' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/babel' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/babel.prod' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/defaults/webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/env' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/globals' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/interpret-files' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/polyfills' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/utils' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/loadCustomBabelConfig' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/loadCustomWebpackConfig' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/middleware' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils' {
  declare module.exports: any;
}

declare module '@storybook/core/env' {
  declare module.exports: any;
}

declare module '@storybook/core/server' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/index' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/manager/index' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/manager/preview' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/manager/provider' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/client_api' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/client_api.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/config_api' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/reducer' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/start' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/story_store' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/story_store.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/subscriptions_store' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/subscriptions_store.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/syncUrlWithStore' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/build-dev' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/build-static' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/babel' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/babel.prod' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/defaults/webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/env' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/globals' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/interpret-files' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/interpret-files.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/polyfills' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/utils' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/loadCustomBabelConfig' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/loadCustomWebpackConfig' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/middleware' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/core/client.js' {
  declare module.exports: $Exports<'@storybook/core/client'>;
}
declare module '@storybook/core/dist/client/index.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/index'>;
}
declare module '@storybook/core/dist/client/manager/index.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/manager/index'>;
}
declare module '@storybook/core/dist/client/manager/preview.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/manager/preview'>;
}
declare module '@storybook/core/dist/client/manager/provider.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/manager/provider'>;
}
declare module '@storybook/core/dist/client/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/actions'>;
}
declare module '@storybook/core/dist/client/preview/client_api.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/client_api'>;
}
declare module '@storybook/core/dist/client/preview/config_api.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/config_api'>;
}
declare module '@storybook/core/dist/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/index'>;
}
declare module '@storybook/core/dist/client/preview/reducer.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/reducer'>;
}
declare module '@storybook/core/dist/client/preview/start.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/start'>;
}
declare module '@storybook/core/dist/client/preview/story_store.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/story_store'>;
}
declare module '@storybook/core/dist/client/preview/subscriptions_store.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/subscriptions_store'>;
}
declare module '@storybook/core/dist/client/preview/syncUrlWithStore.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/syncUrlWithStore'>;
}
declare module '@storybook/core/dist/server/build-dev.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/build-dev'>;
}
declare module '@storybook/core/dist/server/build-static.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/build-static'>;
}
declare module '@storybook/core/dist/server/config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config'>;
}
declare module '@storybook/core/dist/server/config/babel.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/babel'>;
}
declare module '@storybook/core/dist/server/config/babel.prod.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/babel.prod'>;
}
declare module '@storybook/core/dist/server/config/defaults/webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/defaults/webpack.config'>;
}
declare module '@storybook/core/dist/server/config/env.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/env'>;
}
declare module '@storybook/core/dist/server/config/globals.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/globals'>;
}
declare module '@storybook/core/dist/server/config/interpret-files.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/interpret-files'>;
}
declare module '@storybook/core/dist/server/config/polyfills.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/polyfills'>;
}
declare module '@storybook/core/dist/server/config/utils.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/utils'>;
}
declare module '@storybook/core/dist/server/config/webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/webpack.config'>;
}
declare module '@storybook/core/dist/server/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/webpack.config.prod'>;
}
declare module '@storybook/core/dist/server/loadCustomBabelConfig.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/loadCustomBabelConfig'>;
}
declare module '@storybook/core/dist/server/loadCustomWebpackConfig.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/loadCustomWebpackConfig'>;
}
declare module '@storybook/core/dist/server/middleware.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/middleware'>;
}
declare module '@storybook/core/dist/server/utils.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils'>;
}
declare module '@storybook/core/env.js' {
  declare module.exports: $Exports<'@storybook/core/env'>;
}
declare module '@storybook/core/server.js' {
  declare module.exports: $Exports<'@storybook/core/server'>;
}
declare module '@storybook/core/src/client/index.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/index'>;
}
declare module '@storybook/core/src/client/manager/index.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/manager/index'>;
}
declare module '@storybook/core/src/client/manager/preview.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/manager/preview'>;
}
declare module '@storybook/core/src/client/manager/provider.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/manager/provider'>;
}
declare module '@storybook/core/src/client/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/actions'>;
}
declare module '@storybook/core/src/client/preview/client_api.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/client_api'>;
}
declare module '@storybook/core/src/client/preview/client_api.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/client_api.test'>;
}
declare module '@storybook/core/src/client/preview/config_api.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/config_api'>;
}
declare module '@storybook/core/src/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/index'>;
}
declare module '@storybook/core/src/client/preview/reducer.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/reducer'>;
}
declare module '@storybook/core/src/client/preview/start.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/start'>;
}
declare module '@storybook/core/src/client/preview/story_store.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/story_store'>;
}
declare module '@storybook/core/src/client/preview/story_store.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/story_store.test'>;
}
declare module '@storybook/core/src/client/preview/subscriptions_store.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/subscriptions_store'>;
}
declare module '@storybook/core/src/client/preview/subscriptions_store.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/subscriptions_store.test'>;
}
declare module '@storybook/core/src/client/preview/syncUrlWithStore.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/syncUrlWithStore'>;
}
declare module '@storybook/core/src/server/build-dev.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/build-dev'>;
}
declare module '@storybook/core/src/server/build-static.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/build-static'>;
}
declare module '@storybook/core/src/server/config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config'>;
}
declare module '@storybook/core/src/server/config/babel.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/babel'>;
}
declare module '@storybook/core/src/server/config/babel.prod.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/babel.prod'>;
}
declare module '@storybook/core/src/server/config/defaults/webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/defaults/webpack.config'>;
}
declare module '@storybook/core/src/server/config/env.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/env'>;
}
declare module '@storybook/core/src/server/config/globals.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/globals'>;
}
declare module '@storybook/core/src/server/config/interpret-files.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/interpret-files'>;
}
declare module '@storybook/core/src/server/config/interpret-files.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/interpret-files.test'>;
}
declare module '@storybook/core/src/server/config/polyfills.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/polyfills'>;
}
declare module '@storybook/core/src/server/config/utils.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/utils'>;
}
declare module '@storybook/core/src/server/config/webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/webpack.config'>;
}
declare module '@storybook/core/src/server/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/webpack.config.prod'>;
}
declare module '@storybook/core/src/server/loadCustomBabelConfig.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/loadCustomBabelConfig'>;
}
declare module '@storybook/core/src/server/loadCustomWebpackConfig.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/loadCustomWebpackConfig'>;
}
declare module '@storybook/core/src/server/middleware.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/middleware'>;
}
declare module '@storybook/core/src/server/utils.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils'>;
}
declare module '@storybook/core/src/server/utils.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils.test'>;
}
